/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const JobsIndexLazyImport = createFileRoute('/jobs/')()
const FailedJobsIndexLazyImport = createFileRoute('/failed-jobs/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const JobsIndexLazyRoute = JobsIndexLazyImport.update({
  path: '/jobs/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/jobs/index.lazy').then((d) => d.Route))

const FailedJobsIndexLazyRoute = FailedJobsIndexLazyImport.update({
  path: '/failed-jobs/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/failed-jobs/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/failed-jobs/': {
      id: '/failed-jobs/'
      path: '/failed-jobs'
      fullPath: '/failed-jobs'
      preLoaderRoute: typeof FailedJobsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/failed-jobs': typeof FailedJobsIndexLazyRoute
  '/jobs': typeof JobsIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/failed-jobs': typeof FailedJobsIndexLazyRoute
  '/jobs': typeof JobsIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/failed-jobs/': typeof FailedJobsIndexLazyRoute
  '/jobs/': typeof JobsIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/failed-jobs' | '/jobs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/failed-jobs' | '/jobs'
  id: '__root__' | '/' | '/about' | '/failed-jobs/' | '/jobs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  FailedJobsIndexLazyRoute: typeof FailedJobsIndexLazyRoute
  JobsIndexLazyRoute: typeof JobsIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  FailedJobsIndexLazyRoute: FailedJobsIndexLazyRoute,
  JobsIndexLazyRoute: JobsIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/failed-jobs/",
        "/jobs/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/failed-jobs/": {
      "filePath": "failed-jobs/index.lazy.tsx"
    },
    "/jobs/": {
      "filePath": "jobs/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
